// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('c:/src/Projects/BrewCrawl/node_modules/react');
var { Component } = React;
var ReactNative = require('c:/src/Projects/BrewCrawl/node_modules/react-native');
var { AppRegistry } = ReactNative;
var entryPoint = require('c:/src/Projects/BrewCrawl/index.js');
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('BrewCrawl', appParameters);
});